### ISSUE TITLE
Zotero.Proxies is undefined

### ISSUE THREAD

**Issue by danmichaelo** [zotero/scaffold#31]
When I press "Test Regex" nothing happens. Looking into the console, the following error is printed when pressing the button:

    TypeError: Zotero.Proxies is undefined
    scaffold.js:465:7

When trying to run detectWeb or doWeb I get

    TypeError: Zotero.Translators.save is not a function
    scaffold.js:343:3

I'm using Scaffold 3.2.3 with Firefox 45.0.1 and Zotero 4.0.29.9 on Mac

**Comment by danmichaelo** [comment]
Closing Zotero standalone and opening Zotero in Firefox seems to help

**Comment by dstillman** [comment]
Scaffold only works with Zotero for Firefox — when Standalone is open, Zotero for Firefox is just running in connector mode and the code Scaffold depends on isn't available.

(We'll have to figure out what happens to Scaffold when there's no more full Zotero for Firefox, but for the moment this is expected behavior.)

**Comment by dstillman** [comment]
(Scaffold could display a better error message here, but since Zotero for Firefox may be going away soon, it's probably not worth bothering.)
