### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#42]
https://github.com/zotero/scaffold/releases

**Comment by zuphilip** [comment]
Maybe now would be a good time to create a new release, as also @adam3smith pointed out...

**Comment by adam3smith** [comment]
Turns out I have push access. Done

**Comment by dstillman** [comment]
You actually created it with the wrong tag (v.3.30 instead of v3.3.0). Can you move the release notes and XPI to the v3.3.0 tag I created?

**Comment by adam3smith** [comment]
ugh, sorry about that. done

**Comment by zuphilip** [comment]
Thank you both!

One thing I didn't understand: What is the reason for the `gh-pages` branch here? I see that we have thereby https://zotero.github.io/scaffold/scaffold.rdf, but for what is this used?

**Comment by dstillman** [comment]
It's the update manifest that tells clients (in this case Zotero) about the new version. Referenced from install.rdf.

**Comment by zuphilip** [comment]
Okay, this step seems missing in the [release.sh](https://github.com/zotero/scaffold/blob/master/release.sh). Should it be added there?

**Comment by dstillman** [comment]
Sure. Note that, if you need to use a regexp in the replace line, it's better to use perl rather than sed (similar to our [other build scripts](https://github.com/zotero/zotero-build/blob/b330e8ec4c979e18578689f15bd1c1e817d30188/xpi/build_xpi_4.0#L72)), and same for grep — macOS has BSD sed/grep rather than GNU by default, so some of the flags are different. The current script produced empty version values for me because of the grep line.

**Comment by dstillman** [comment]
And the shasum command can also be different between Cygwin, macOS, and Linux, so you'd want to use [this](https://github.com/zotero/zotero-build/blob/b330e8ec4c979e18578689f15bd1c1e817d30188/xpi/build_xpi_4.0#L213).

**Comment by zuphilip** [comment]
Okay, thank you for the info. I created an issue about these.
