### ISSUE TITLE
Display HTML source instead of rendered page in Browser tab

### ISSUE THREAD

**Issue by adomasven** [zotero/scaffold#97]
In light of https://github.com/zotero/translators/issues/1728 does it (will it?) make sense to display the rendered page in the Browser tab rather than the HTML source? Is the rendered page there at least useful now? Would HTML source be more helpful?

**Comment by dstillman** [comment]
Interesting idea (and we could do it trivially, since `view-source:[url]` works there already). I think, though, that the main thing purpose of the Browser pane is to let you log in and run translation against a logged-in version, and a source-only view wouldn't allow that. And if you're viewing the source for actual development, you might as well be doing it in the browser where you can use the devtools to test selectors, etc.

But there might be a way to get the original source somewhere in the nsIChannel or Document and just parse that to pass to translation. View Source doesn't trigger a reload, at least on some sites, but I'm not sure whether that's always the case or if it only happens when the site allows caching and it can just reload from the cache.

**Comment by zuphilip** [comment]
There are websites where different content is presented under the same URL. Thus, one has to first e.g. perform a search and then click to a result, which then can be used to for testing during writing the translator code. I can't remember to log in to some website in Scaffold, but @adam3smith worked more with ResearchGate where it makes a difference, whether you are logged in or not.

I can't imagine to just work with the source code of a website. That is usually too cluttered, I guess. Even in the DOM object if the nesting is nicely visualized, the ordering and placement on a website might be highly influenced on some CSS. These are my first thoughts, but I am happy to test in practice any idea you have.

Is the effect we are looking for the same as to load the website in the browser but deactivate JS, e.g. with NoScript plugin?

**Comment by adam3smith** [comment]
right, I do all my actual poking at the site in Firefox where I have inspect element and the Network console. What I see in the browser window is a) for authentication (also for proxy when working remotely) and b) to make sure I'm looking at the same thing as in the browser. For both of those purposes, the HTML source isn't much help at all, so I'd much rather not do this.

**Comment by adomasven** [comment]
Ok, it seems I misjudged the usefulness of the browser.
